# Generated by Django 3.1.7 on 2021-06-23 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Secret',
            fields=[
                ('uuid', models.CharField(max_length=100)),
                ('secret', models.CharField(max_length=500)),
                ('access_key', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('secret_created_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
