# Generated by Django 3.1.7 on 2021-06-23 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secret_keeper', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='secret',
            name='access_key',
            field=models.CharField(max_length=128, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='secret',
            name='secret',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='secret',
            name='uuid',
            field=models.CharField(max_length=32),
        ),
    ]
